name: geohack
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter-book
  - matplotlib
  - numpy
  - ghp-import
  - xarray
  - rioxarray
  - zarr
  - cftime
  - nc-time-axis
  - netcdf4
  - h5netcdf
  - cartopy
  - holoviews
  - hvplot
  - geoviews
  - cartopy
  - geopandas
  - intake
  - intake-esm
  - pooch
  - dask
  - kerchunk
  - fsspec
  - s3fs
  - git
  - jupyterlab-git
  - "nodejs>=16,<17"
  - jupyterlab-myst>=2.0.0
  - "ipywidgets>=7.6.0,<8"
  - odc-stac
  - pip
  - pip:
      - wget
      - sphinx-exercise
      - jupytext
      - nbgitpuller
      - mystmd
      - pystac-client
